### ISSUE TITLE
Wunderground PWS

### ISSUE THREAD

**Issue by Quarx64** [saxn-paule/pimatic-wunderground#1]
Da gibt es Optionen für Private Weather Stations, siehe hier.
https://www.wunderground.com/personal-weather-station/dashboard?ID=IBOGEN8
Da geht das aktuelle Wetter noch genauer, weil wie in diesem Fall  die pws nur einige Meter von mir zu hause entfernt ist.
Kannst du in den Device Settings noch den Parameter "pws" einfügen.
Bei der Abfrage der Wetterdaten muss dann an den Link noch "/q/pws:" + myoptions.pws angehängt werden.

**Comment by saxn-paule** [comment]
Done. Have a look at version 0.0.8. Feedback is welcome.
